"""milestone 3 webhook inbox and outbox

Revision ID: a038dd8ec971
Revises: cee67bdeeb49
Create Date: 2026-09-04 11:04:14.715466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a038dd8ec971'
down_revision: Union[str, Sequence[str], None] = 'cee67bdeeb49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PUBLISHED', 'FAILED', name='outboxeventstatus', native_enum=False, create_constraint=True, length=32), server_default='PENDING', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('attempts >= 0', name='ck_outbox_events_attempts_nonnegative'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_outbox_events_merchant_id'), 'outbox_events', ['merchant_id'], unique=False)
    op.create_index('ix_outbox_events_merchant_status', 'outbox_events', ['merchant_id', 'status'], unique=False)
    op.create_index('ix_outbox_events_status_created_at', 'outbox_events', ['status', 'created_at'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=32), server_default='razorpay', nullable=False),
    sa.Column('provider_event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'PROCESSED', 'IGNORED', 'FAILED', name='webhookeventstatus', native_enum=False, create_constraint=True, length=32), server_default='RECEIVED', nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_webhook_events_provider_event')
    )
    op.create_index('ix_webhook_events_merchant_event_type', 'webhook_events', ['merchant_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_merchant_id'), 'webhook_events', ['merchant_id'], unique=False)
    op.create_index('ix_webhook_events_merchant_status', 'webhook_events', ['merchant_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_index('ix_webhook_events_merchant_status', table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_merchant_id'), table_name='webhook_events')
    op.drop_index('ix_webhook_events_merchant_event_type', table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index('ix_outbox_events_status_created_at', table_name='outbox_events')
    op.drop_index('ix_outbox_events_merchant_status', table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_merchant_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    # ### end Alembic commands ###
