"""core recovery schema

Revision ID: cee67bdeeb49
Revises: 
Create Date: 2026-09-02 15:26:05.182708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cee67bdeeb49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('actor', sa.String(length=64), server_default='system', nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_events_merchant_created_at', 'audit_events', ['merchant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_merchant_id'), 'audit_events', ['merchant_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=32), server_default='razorpay', nullable=False),
    sa.Column('provider_payment_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'FAILED', 'CAPTURED', name='paymentstatus', native_enum=False, create_constraint=True, length=32), server_default='CREATED', nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('failure_code', sa.String(length=128), nullable=True),
    sa.Column('failure_reason', sa.String(length=512), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name='ck_payments_currency_three_uppercase'),
    sa.CheckConstraint('amount_minor >= 0', name='ck_payments_amount_minor_nonnegative'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'provider', 'provider_payment_id', name='uq_payments_merchant_provider_payment')
    )
    op.create_index(op.f('ix_payments_merchant_id'), 'payments', ['merchant_id'], unique=False)
    op.create_index('ix_payments_merchant_status', 'payments', ['merchant_id', 'status'], unique=False)
    op.create_table('recovery_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('FAILED', 'ELIGIBLE', 'ANALYSING', 'ACTION_SELECTED', 'ACTION_SCHEDULED', 'WAITING', 'RECOVERED', 'STOPPED', 'ESCALATED', name='recoverycasestatus', native_enum=False, create_constraint=True, length=32), server_default='FAILED', nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('failure_category', sa.String(length=128), nullable=True),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name='ck_recovery_cases_currency_three_uppercase'),
    sa.CheckConstraint('amount_minor >= 0', name='ck_recovery_cases_amount_minor_nonnegative'),
    sa.CheckConstraint('version > 0', name='ck_recovery_cases_version_positive'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id', name='uq_recovery_cases_payment_id')
    )
    op.create_index(op.f('ix_recovery_cases_merchant_id'), 'recovery_cases', ['merchant_id'], unique=False)
    op.create_index('ix_recovery_cases_merchant_status_next', 'recovery_cases', ['merchant_id', 'status', 'next_action_at'], unique=False)
    op.create_index('ix_recovery_cases_status_next_action_at', 'recovery_cases', ['status', 'next_action_at'], unique=False)
    op.create_table('recovery_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('recovery_case_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.Enum('WAIT', 'CREATE_PAYMENT_LINK', 'SEND_REMINDER', 'STOP', 'ESCALATE', name='recoveryactiontype', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', 'EXECUTING', 'EXECUTED', 'FAILED', 'CANCELLED', name='recoveryactionstatus', native_enum=False, create_constraint=True, length=32), server_default='PENDING', nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('attempt_number', sa.Integer(), server_default='1', nullable=False),
    sa.Column('provider_reference', sa.String(length=128), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt_number > 0', name='ck_recovery_actions_attempt_number_positive'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('recovery_case_id', 'action_type', 'attempt_number', name='uq_recovery_actions_case_type_attempt')
    )
    op.create_index('ix_recovery_actions_case_status', 'recovery_actions', ['recovery_case_id', 'status'], unique=False)
    op.create_index(op.f('ix_recovery_actions_merchant_id'), 'recovery_actions', ['merchant_id'], unique=False)
    op.create_index('ix_recovery_actions_merchant_status', 'recovery_actions', ['merchant_id', 'status'], unique=False)
    op.create_index(op.f('ix_recovery_actions_recovery_case_id'), 'recovery_actions', ['recovery_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_actions_recovery_case_id'), table_name='recovery_actions')
    op.drop_index('ix_recovery_actions_merchant_status', table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_merchant_id'), table_name='recovery_actions')
    op.drop_index('ix_recovery_actions_case_status', table_name='recovery_actions')
    op.drop_table('recovery_actions')
    op.drop_index('ix_recovery_cases_status_next_action_at', table_name='recovery_cases')
    op.drop_index('ix_recovery_cases_merchant_status_next', table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_merchant_id'), table_name='recovery_cases')
    op.drop_table('recovery_cases')
    op.drop_index('ix_payments_merchant_status', table_name='payments')
    op.drop_index(op.f('ix_payments_merchant_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_audit_events_merchant_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_merchant_created_at', table_name='audit_events')
    op.drop_index('ix_audit_events_entity', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('merchants')
    # ### end Alembic commands ###
