"""outbox deliver_at

Revision ID: deeabd8cc35e
Revises: fce6482ccae7
Create Date: 2026-09-05 05:29:48.990983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deeabd8cc35e'
down_revision: Union[str, Sequence[str], None] = 'fce6482ccae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('deliver_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_outbox_events_status_deliver_at', 'outbox_events', ['status', 'deliver_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_events_status_deliver_at', table_name='outbox_events')
    op.drop_column('outbox_events', 'deliver_at')
    # ### end Alembic commands ###
