"""merchant policies

Revision ID: fce6482ccae7
Revises: a038dd8ec971
Create Date: 2026-09-05 02:33:06.469399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fce6482ccae7'
down_revision: Union[str, Sequence[str], None] = 'a038dd8ec971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('max_actions_per_case', sa.Integer(), server_default='3', nullable=False),
    sa.Column('max_reminders_per_case', sa.Integer(), server_default='2', nullable=False),
    sa.Column('one_active_payment_link', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('high_value_escalation_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('high_value_threshold_minor', sa.BigInteger(), server_default='500000', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('high_value_threshold_minor >= 0', name='ck_merchant_policies_high_value_threshold_nonnegative'),
    sa.CheckConstraint('max_actions_per_case >= 0', name='ck_merchant_policies_max_actions_nonnegative'),
    sa.CheckConstraint('max_reminders_per_case >= 0', name='ck_merchant_policies_max_reminders_nonnegative'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', name='uq_merchant_policies_merchant_id')
    )
    op.create_index(op.f('ix_merchant_policies_merchant_id'), 'merchant_policies', ['merchant_id'], unique=False)
    op.drop_constraint(op.f('outboxeventstatus'), 'outbox_events', type_='check')
    op.drop_constraint(op.f('paymentstatus'), 'payments', type_='check')
    op.drop_constraint(op.f('recoveryactionstatus'), 'recovery_actions', type_='check')
    op.drop_constraint(op.f('recoveryactiontype'), 'recovery_actions', type_='check')
    op.drop_constraint(op.f('recoverycasestatus'), 'recovery_cases', type_='check')
    op.drop_constraint(op.f('webhookeventstatus'), 'webhook_events', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('webhookeventstatus'), 'webhook_events', "status::text = ANY (ARRAY['RECEIVED'::character varying, 'PROCESSED'::character varying, 'IGNORED'::character varying, 'FAILED'::character varying]::text[])")
    op.create_check_constraint(op.f('recoverycasestatus'), 'recovery_cases', "status::text = ANY (ARRAY['FAILED'::character varying::text, 'ELIGIBLE'::character varying::text, 'ANALYSING'::character varying::text, 'ACTION_SELECTED'::character varying::text, 'ACTION_SCHEDULED'::character varying::text, 'WAITING'::character varying::text, 'RECOVERED'::character varying::text, 'STOPPED'::character varying::text, 'ESCALATED'::character varying::text])")
    op.create_check_constraint(op.f('recoveryactiontype'), 'recovery_actions', "action_type::text = ANY (ARRAY['WAIT'::character varying::text, 'CREATE_PAYMENT_LINK'::character varying::text, 'SEND_REMINDER'::character varying::text, 'STOP'::character varying::text, 'ESCALATE'::character varying::text])")
    op.create_check_constraint(op.f('recoveryactionstatus'), 'recovery_actions', "status::text = ANY (ARRAY['PENDING'::character varying::text, 'APPROVED'::character varying::text, 'DENIED'::character varying::text, 'EXECUTING'::character varying::text, 'EXECUTED'::character varying::text, 'FAILED'::character varying::text, 'CANCELLED'::character varying::text])")
    op.create_check_constraint(op.f('paymentstatus'), 'payments', "status::text = ANY (ARRAY['CREATED'::character varying::text, 'FAILED'::character varying::text, 'CAPTURED'::character varying::text])")
    op.create_check_constraint(op.f('outboxeventstatus'), 'outbox_events', "status::text = ANY (ARRAY['PENDING'::character varying, 'PUBLISHED'::character varying, 'FAILED'::character varying]::text[])")
    op.drop_index(op.f('ix_merchant_policies_merchant_id'), table_name='merchant_policies')
    op.drop_table('merchant_policies')
    # ### end Alembic commands ###
